//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicShop.Resource.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy cập bị từ chối!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã đăng ký tài khoản.
        /// </summary>
        public static string AccountExist {
            get {
                return ResourceManager.GetString("AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị vô hiệu hóa!.
        /// </summary>
        public static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hiện đang bị khóa,  vui lòng liên hệ Quản trị viên để được trợ giúp!.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này chưa được đăng ký. Vui lòng đăng ký tài khoản.
        /// </summary>
        public static string AccountNotExist {
            get {
                return ResourceManager.GetString("AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không thuộc trang web này (có thể là Insites), vùi lòng kiểm tra lại hoặc liên hệ Quản trị viên để được trợ giúp!.
        /// </summary>
        public static string AccountNotInCurrentWebsite {
            get {
                return ResourceManager.GetString("AccountNotInCurrentWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không hợp lệ, vui lòng liên hệ Quản trị viên để được trợ giúp!.
        /// </summary>
        public static string ActivateAccountFail {
            get {
                return ResourceManager.GetString("ActivateAccountFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thấy bại.
        /// </summary>
        public static string ChangePasswordFail {
            get {
                return ResourceManager.GetString("ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã code này đã tồn tại trên hệ thống, vui lòng nhập mã khác!.
        /// </summary>
        public static string CodeExisted {
            get {
                return ResourceManager.GetString("CodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và xác nhận mật khẩu không khớp, hãy kiểm tra và thử lại!.
        /// </summary>
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu!.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thất bại!.
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bị trùng lặp dữ liệu, vui lòng liên hệ quản trị viên để được hỗ trợ!.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại, vui lòng thử lại bằng một email khác!.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này đã được đăng ký ở hệ thống CTV, vui lòng thử bằng Email khác, hoặc liên hệ quản trị viên để được hỗ trợ!.
        /// </summary>
        public static string EmailExistsInCTV {
            get {
                return ResourceManager.GetString("EmailExistsInCTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này đã được đăng ký ở hệ thống Insites, vui lòng thử bằng Email khác, hoặc liên hệ quản trị viên để được hỗ trợ!.
        /// </summary>
        public static string EmailExistsInERP {
            get {
                return ResourceManager.GetString("EmailExistsInERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại!.
        /// </summary>
        public static string EmailNotExsits {
            get {
                return ResourceManager.GetString("EmailNotExsits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy Email hoặc số điện thoại, vui lòng kiểm tra lại!.
        /// </summary>
        public static string EmailOrPhoneNotFound {
            get {
                return ResourceManager.GetString("EmailOrPhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp ảnh không hợp lệ hoặc ảnh có dung lượng quá lớn (&gt;2MB).
        /// </summary>
        public static string ImageInvalid {
            get {
                return ResourceManager.GetString("ImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới thất bại, lỗi không xác định!.
        /// </summary>
        public static string InsertFail {
            get {
                return ResourceManager.GetString("InsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng!.
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kỹ thuật: tham số NULL.
        /// </summary>
        public static string ParameterNull {
            get {
                return ResourceManager.GetString("ParameterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác. Vui lòng nhập đúng mật khẩu.
        /// </summary>
        public static string PasswordFail {
            get {
                return ResourceManager.GetString("PasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền không xác định!.
        /// </summary>
        public static string PermissionUnknow {
            get {
                return ResourceManager.GetString("PermissionUnknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại trong hệ thống, vui lòng thử một số điện thoại khác!.
        /// </summary>
        public static string PhoneNumberExists {
            get {
                return ResourceManager.GetString("PhoneNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại này đã được đăng ký ở hệ thống CTV, vui lòng thử bằng Số điện thoại khác, hoặc liên hệ quản trị viên để được hỗ trợ!.
        /// </summary>
        public static string PhoneNumberExistsInCTV {
            get {
                return ResourceManager.GetString("PhoneNumberExistsInCTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại này đã được đăng ký ở hệ thống Insites, vui lòng thử bằng Số điện thoại khác, hoặc liên hệ quản trị viên để được hỗ trợ!.
        /// </summary>
        public static string PhoneNumberExistsInERP {
            get {
                return ResourceManager.GetString("PhoneNumberExistsInERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh mục này đang được gán cho các sản phẩm khác, vui lòng không xóa!.
        /// </summary>
        public static string ProductExist {
            get {
                return ResourceManager.GetString("ProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm này đang ở trạng thái công khai nên không thể xóa, vui lòng cập nhật lại trạng thái nếu bạn muốn thực hiện hành động này!.
        /// </summary>
        public static string ProductIsPublished {
            get {
                return ResourceManager.GetString("ProductIsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thất bại, vui lòng thử lại sau giây lát!.
        /// </summary>
        public static string RegisterFail {
            get {
                return ResourceManager.GetString("RegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu thất bại!.
        /// </summary>
        public static string ResetPasswordFail {
            get {
                return ResourceManager.GetString("ResetPasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò đã tồn tại.
        /// </summary>
        public static string RoleExisted {
            get {
                return ResourceManager.GetString("RoleExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đăng nhập/Token hết hạn!.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không xác định.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại, lỗi không xác định!.
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi tải lên, vui lòng đợi trong giây lát và thử lại!.
        /// </summary>
        public static string UploadFileError {
            get {
                return ResourceManager.GetString("UploadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài khoản!.
        /// </summary>
        public static string User_StaffNotFound {
            get {
                return ResourceManager.GetString("User/StaffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản đã tồn tại! Vui lòng chọn tên tài khoản khác!.
        /// </summary>
        public static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống hiện không thể khởi tạo Username mới cho bạn, vui lòng thử lại sau giây lát!.
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không đúng, vui lòng kiểm tra và thử lại!.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
