//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicShop.Resource.PermissionsResx", typeof(PermissionsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.assign.
        /// </summary>
        public static string AssignRole {
            get {
                return ResourceManager.GetString("AssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appointment.create.
        /// </summary>
        public static string CreateAppointment {
            get {
                return ResourceManager.GetString("CreateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand.create.
        /// </summary>
        public static string CreateBrand {
            get {
                return ResourceManager.GetString("CreateBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.color.create.
        /// </summary>
        public static string CreateCarColor {
            get {
                return ResourceManager.GetString("CreateCarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.grade.create.
        /// </summary>
        public static string CreateCarGrade {
            get {
                return ResourceManager.GetString("CreateCarGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.image.create.
        /// </summary>
        public static string CreateCarImage {
            get {
                return ResourceManager.GetString("CreateCarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.model.create.
        /// </summary>
        public static string CreateCarModel {
            get {
                return ResourceManager.GetString("CreateCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.centerserives.create.
        /// </summary>
        public static string CreateCenterSerives {
            get {
                return ResourceManager.GetString("CreateCenterSerives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.create.
        /// </summary>
        public static string CreateCustommer {
            get {
                return ResourceManager.GetString("CreateCustommer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.template.create.
        /// </summary>
        public static string CreateEmailTemplate {
            get {
                return ResourceManager.GetString("CreateEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.create.
        /// </summary>
        public static string CreateLocation {
            get {
                return ResourceManager.GetString("CreateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintainence.create.
        /// </summary>
        public static string CreateMaintainence {
            get {
                return ResourceManager.GetString("CreateMaintainence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.template.create.
        /// </summary>
        public static string CreateNotificationTemplate {
            get {
                return ResourceManager.GetString("CreateNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.create.
        /// </summary>
        public static string CreateNotify {
            get {
                return ResourceManager.GetString("CreateNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to org.create.
        /// </summary>
        public static string CreateOrganization {
            get {
                return ResourceManager.GetString("CreateOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.productandservice.create.
        /// </summary>
        public static string CreateProductAndService {
            get {
                return ResourceManager.GetString("CreateProductAndService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.create.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.signallight.create.
        /// </summary>
        public static string CreateSignalLight {
            get {
                return ResourceManager.GetString("CreateSignalLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.create.
        /// </summary>
        public static string CreateSurvey {
            get {
                return ResourceManager.GetString("CreateSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.question.create.
        /// </summary>
        public static string CreateSurveyQuestion {
            get {
                return ResourceManager.GetString("CreateSurveyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.create.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.usermanual.create.
        /// </summary>
        public static string CreateUserManual {
            get {
                return ResourceManager.GetString("CreateUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warranty.info.create.
        /// </summary>
        public static string CreateWarrantyInfo {
            get {
                return ResourceManager.GetString("CreateWarrantyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warranty.policy.create.
        /// </summary>
        public static string CreateWarrantyPolicy {
            get {
                return ResourceManager.GetString("CreateWarrantyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appointment.delete.
        /// </summary>
        public static string DeleteAppointment {
            get {
                return ResourceManager.GetString("DeleteAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand.delete.
        /// </summary>
        public static string DeleteBrand {
            get {
                return ResourceManager.GetString("DeleteBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.color.delete.
        /// </summary>
        public static string DeleteCarColor {
            get {
                return ResourceManager.GetString("DeleteCarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.grade.delete.
        /// </summary>
        public static string DeleteCarGrade {
            get {
                return ResourceManager.GetString("DeleteCarGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.image.delete.
        /// </summary>
        public static string DeleteCarImage {
            get {
                return ResourceManager.GetString("DeleteCarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.model.delete.
        /// </summary>
        public static string DeleteCarModel {
            get {
                return ResourceManager.GetString("DeleteCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.centerserives.delete.
        /// </summary>
        public static string DeleteCenterSerives {
            get {
                return ResourceManager.GetString("DeleteCenterSerives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.delete.
        /// </summary>
        public static string DeleteCustommer {
            get {
                return ResourceManager.GetString("DeleteCustommer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.template.delete.
        /// </summary>
        public static string DeleteEmailTemplate {
            get {
                return ResourceManager.GetString("DeleteEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.delete.
        /// </summary>
        public static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintainence.delete.
        /// </summary>
        public static string DeleteMaintainence {
            get {
                return ResourceManager.GetString("DeleteMaintainence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehiclecustomerinfo.maintainence.delete.
        /// </summary>
        public static string DeleteMaintainenceHistoryCustomer {
            get {
                return ResourceManager.GetString("DeleteMaintainenceHistoryCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.template.delete.
        /// </summary>
        public static string DeleteNotificationTemplate {
            get {
                return ResourceManager.GetString("DeleteNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.delete.
        /// </summary>
        public static string DeleteNotify {
            get {
                return ResourceManager.GetString("DeleteNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to org.delete.
        /// </summary>
        public static string DeleteOrganization {
            get {
                return ResourceManager.GetString("DeleteOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.productandservice.delete.
        /// </summary>
        public static string DeleteProductAndService {
            get {
                return ResourceManager.GetString("DeleteProductAndService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.delete.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.signallight.delete.
        /// </summary>
        public static string DeleteSignalLight {
            get {
                return ResourceManager.GetString("DeleteSignalLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.delete.
        /// </summary>
        public static string DeleteSurvey {
            get {
                return ResourceManager.GetString("DeleteSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.question.delete.
        /// </summary>
        public static string DeleteSurveyQuestion {
            get {
                return ResourceManager.GetString("DeleteSurveyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.usermanual.delete.
        /// </summary>
        public static string DeleteUserManual {
            get {
                return ResourceManager.GetString("DeleteUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warranty.info.delete.
        /// </summary>
        public static string DeleteWarrantyInfo {
            get {
                return ResourceManager.GetString("DeleteWarrantyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warranty.policy.delete.
        /// </summary>
        public static string DeleteWarrantyPolicy {
            get {
                return ResourceManager.GetString("DeleteWarrantyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.app.
        /// </summary>
        public static string EditAppConfig {
            get {
                return ResourceManager.GetString("EditAppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appointment.edit.
        /// </summary>
        public static string EditAppointment {
            get {
                return ResourceManager.GetString("EditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand.edit.
        /// </summary>
        public static string EditBrand {
            get {
                return ResourceManager.GetString("EditBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.color.edit.
        /// </summary>
        public static string EditCarColor {
            get {
                return ResourceManager.GetString("EditCarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.grade.edit.
        /// </summary>
        public static string EditCarGrade {
            get {
                return ResourceManager.GetString("EditCarGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.image.edit.
        /// </summary>
        public static string EditCarImage {
            get {
                return ResourceManager.GetString("EditCarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.model.edit.
        /// </summary>
        public static string EditCarModel {
            get {
                return ResourceManager.GetString("EditCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.centerserives.edit.
        /// </summary>
        public static string EditCenterSerives {
            get {
                return ResourceManager.GetString("EditCenterSerives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.edit.
        /// </summary>
        public static string EditCustommer {
            get {
                return ResourceManager.GetString("EditCustommer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.email.
        /// </summary>
        public static string EditEmailConfig {
            get {
                return ResourceManager.GetString("EditEmailConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.template.edit.
        /// </summary>
        public static string EditEmailTemplate {
            get {
                return ResourceManager.GetString("EditEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.edit.
        /// </summary>
        public static string EditLocation {
            get {
                return ResourceManager.GetString("EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintainence.edit.
        /// </summary>
        public static string EditMaintainence {
            get {
                return ResourceManager.GetString("EditMaintainence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehiclecustomerinfo.maintainence.edit.
        /// </summary>
        public static string EditMaintainenceHistoryCustomer {
            get {
                return ResourceManager.GetString("EditMaintainenceHistoryCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.template.edit.
        /// </summary>
        public static string EditNotificationTemplate {
            get {
                return ResourceManager.GetString("EditNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.edit.
        /// </summary>
        public static string EditNotify {
            get {
                return ResourceManager.GetString("EditNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to org.edit.
        /// </summary>
        public static string EditOrganization {
            get {
                return ResourceManager.GetString("EditOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.productandservice.edit.
        /// </summary>
        public static string EditProductAndService {
            get {
                return ResourceManager.GetString("EditProductAndService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.edit.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.signallight.edit.
        /// </summary>
        public static string EditSignalLight {
            get {
                return ResourceManager.GetString("EditSignalLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.sms.
        /// </summary>
        public static string EditSmsConfig {
            get {
                return ResourceManager.GetString("EditSmsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.edit.
        /// </summary>
        public static string EditSurvey {
            get {
                return ResourceManager.GetString("EditSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.question.edit.
        /// </summary>
        public static string EditSurveyQuestion {
            get {
                return ResourceManager.GetString("EditSurveyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.edit.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.usermanual.edit.
        /// </summary>
        public static string EditUserManual {
            get {
                return ResourceManager.GetString("EditUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehiclecustomerinfo.edit.
        /// </summary>
        public static string EditVehicleCustomer {
            get {
                return ResourceManager.GetString("EditVehicleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicleinfo.edit.
        /// </summary>
        public static string EditVehicleInfo {
            get {
                return ResourceManager.GetString("EditVehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warranty.info.edit.
        /// </summary>
        public static string EditWarrantyInfo {
            get {
                return ResourceManager.GetString("EditWarrantyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warranty.policy.edit.
        /// </summary>
        public static string EditWarrantyPolicy {
            get {
                return ResourceManager.GetString("EditWarrantyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.activeapp.company.export.
        /// </summary>
        public static string ExportDashboardAciveAppCompany {
            get {
                return ResourceManager.GetString("ExportDashboardAciveAppCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehiclecustomerinfo.insert.
        /// </summary>
        public static string MappingVehicleCustomer {
            get {
                return ResourceManager.GetString("MappingVehicleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehiclecustomerinfo.delete.
        /// </summary>
        public static string RemoveVehicleCustomer {
            get {
                return ResourceManager.GetString("RemoveVehicleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.send.
        /// </summary>
        public static string SendNotify {
            get {
                return ResourceManager.GetString("SendNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncdata.sync.
        /// </summary>
        public static string SyncData {
            get {
                return ResourceManager.GetString("SyncData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncdata.mapping.color.
        /// </summary>
        public static string SyncDataMappingColor {
            get {
                return ResourceManager.GetString("SyncDataMappingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncdata.mapping.grade.
        /// </summary>
        public static string SyncDataMappingGrade {
            get {
                return ResourceManager.GetString("SyncDataMappingGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.view.
        /// </summary>
        public static string ViewConfig {
            get {
                return ResourceManager.GetString("ViewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.view.
        /// </summary>
        public static string ViewCustommer {
            get {
                return ResourceManager.GetString("ViewCustommer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.activeapp.
        /// </summary>
        public static string ViewDashboardActiveApp {
            get {
                return ResourceManager.GetString("ViewDashboardActiveApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.activeapp.company.
        /// </summary>
        public static string ViewDashboardActiveAppCompany {
            get {
                return ResourceManager.GetString("ViewDashboardActiveAppCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.appointment.
        /// </summary>
        public static string ViewDashboardAppointment {
            get {
                return ResourceManager.GetString("ViewDashboardAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.appointment.detail.
        /// </summary>
        public static string ViewDashboardAppointmentDetail {
            get {
                return ResourceManager.GetString("ViewDashboardAppointmentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logactivity.app.list.view.
        /// </summary>
        public static string ViewListAppLogAcitivity {
            get {
                return ResourceManager.GetString("ViewListAppLogAcitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appointment.list.view.
        /// </summary>
        public static string ViewListAppointment {
            get {
                return ResourceManager.GetString("ViewListAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand.list.view.
        /// </summary>
        public static string ViewListBrand {
            get {
                return ResourceManager.GetString("ViewListBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.color.list.view.
        /// </summary>
        public static string ViewListCarColor {
            get {
                return ResourceManager.GetString("ViewListCarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.grade.list.view.
        /// </summary>
        public static string ViewListCarGrade {
            get {
                return ResourceManager.GetString("ViewListCarGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.image.list.view.
        /// </summary>
        public static string ViewListCarImage {
            get {
                return ResourceManager.GetString("ViewListCarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.model.list.view.
        /// </summary>
        public static string ViewListCarModel {
            get {
                return ResourceManager.GetString("ViewListCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.centerserives.list.view.
        /// </summary>
        public static string ViewListCenterSerives {
            get {
                return ResourceManager.GetString("ViewListCenterSerives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.list.view.
        /// </summary>
        public static string ViewListCustomer {
            get {
                return ResourceManager.GetString("ViewListCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.template.list.view.
        /// </summary>
        public static string ViewListEmailTemplate {
            get {
                return ResourceManager.GetString("ViewListEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.list.view.
        /// </summary>
        public static string ViewListLocation {
            get {
                return ResourceManager.GetString("ViewListLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintainence.list.view.
        /// </summary>
        public static string ViewListMaintainence {
            get {
                return ResourceManager.GetString("ViewListMaintainence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.template.list.view.
        /// </summary>
        public static string ViewListNoficationTempate {
            get {
                return ResourceManager.GetString("ViewListNoficationTempate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify.list.view.
        /// </summary>
        public static string ViewListNotify {
            get {
                return ResourceManager.GetString("ViewListNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to org.list.view.
        /// </summary>
        public static string ViewListOrganization {
            get {
                return ResourceManager.GetString("ViewListOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.productandservice.list.view.
        /// </summary>
        public static string ViewListProductAndService {
            get {
                return ResourceManager.GetString("ViewListProductAndService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.signallight.list.view.
        /// </summary>
        public static string ViewListSignalLight {
            get {
                return ResourceManager.GetString("ViewListSignalLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.list.view.
        /// </summary>
        public static string ViewListSurvey {
            get {
                return ResourceManager.GetString("ViewListSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.question.list.view.
        /// </summary>
        public static string ViewListSurveyQuestion {
            get {
                return ResourceManager.GetString("ViewListSurveyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncdata.list.view.
        /// </summary>
        public static string ViewListSyncData {
            get {
                return ResourceManager.GetString("ViewListSyncData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.list.view.
        /// </summary>
        public static string ViewListUser {
            get {
                return ResourceManager.GetString("ViewListUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc.usermanual.list.view.
        /// </summary>
        public static string ViewListUserManual {
            get {
                return ResourceManager.GetString("ViewListUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warranty.info.list.view.
        /// </summary>
        public static string ViewListWarrantyInfo {
            get {
                return ResourceManager.GetString("ViewListWarrantyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warranty.policy.list.view.
        /// </summary>
        public static string ViewListWarrantyPolicy {
            get {
                return ResourceManager.GetString("ViewListWarrantyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.view.
        /// </summary>
        public static string ViewRole {
            get {
                return ResourceManager.GetString("ViewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.view.
        /// </summary>
        public static string ViewUser {
            get {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }
    }
}
